version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4000:4000'
        env_file:
            - .env
        volumes:
            - ./prisma/dev.db:/app/prisma/dev.db:rw # Mount the database file with correct ownership
            - .:/app
            - /app/node_modules
        command: npm run dev