version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: api_development
        ports:
            - "3000:3000"
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
            - /frontend
        command: npm run start:dev
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: weroad
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready", "-d", "weroad" ]
            interval: 30s
            timeout: 60s
            retries: 5
            start_period: 20s
    client:
        build:
            context: .
            dockerfile: Dockerfile
            target: client_development
        ports:
            - "8080:8080"
        env_file:
            - ./frontend/.env
        volumes:
            - ./frontend:/app
            - /app/node_modules
        command: npm run dev
volumes:
    pgdata:
        driver: local